name = "must-work-cache"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "8f0cd6b783d20fe2ea5f2808f5d2eeaf"

routes = [
  "theindiamirror.com/homescrtopnews/*",
  "www.theindiamirror.com/homescrtopnews/*"
]

[triggers]
crons = ["*/30 * * * *"]

[env.production]
zone_id = "3645bf7221290dd864d3de869cba2a84"
