name = "must-work-cache"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "8f0cd6b783d20fe2ea5f2808f5d2eeaf"
routes = ["www.theindiamirror.com/homescrtopnews/*"]
[triggers]
crons = ["*/30 * * * *"]
